### ISSUE TITLE
prime_line relative vs absolute positioning

### ISSUE THREAD

**Issue by numanair** [boardthatpowder/klipper-firmware#1]
Hi, I was looking at your config for reference on prime lines. The prime_line g-code macro is using G91 relative positioning, but the commands seem to make more sense as G90 absolute position coordinates. Is this correct?

**Comment by boardthatpowder** [comment]
Hi, either relative or absolute can be used.  I prefer relative so when setting up new printers you only need to be worried about the start position, but guess its personal preference :).
